### ISSUE TITLE
opencv

### ISSUE THREAD

**Issue by jwijffels** [r-windows/rtools-packages#10]
are there any plans to adding opencv?

**Comment by jeroen** [comment]
Yes certainly, but first I'm focusing on supporting existing CRAN packages.

**Comment by jwijffels** [comment]
Great. Looking forward to it.

**Comment by jeroen** [comment]
I have add a basic build of opencv with not too many external dependencies. Also added a backport for gcc 4.9.3 which has been published on https://github.com/rwinlib/opencv

To test it run:

```r
remotes::install_github("ropenscilabs/opencv")
```

**Comment by jwijffels** [comment]
WoW, will test it out

**Comment by jeroen** [comment]
This is also on cran now, so we can start doing real development on it if you'd like.

**Comment by jwijffels** [comment]
Yes tested this out yesterday by installing the source tarball from CRAN. That installation worked out fine :). 
Then I was testing out using 3.6 testing (blame jeroen) and I hadn't got all dependencies installed yet with that new rtools to make that installation run smoothly.
Do you want to move the discussion of development to ropensci/opencv?

**Comment by jeroen** [comment]
Yes please.
