### ISSUE TITLE
Add gendef.exe

### ISSUE THREAD

**Issue by Maxime2506** [r-windows/rtools-packages#105]
Hi,

I've been trying to install XGboost GPU for R for the last couple of days. Actually gendef.exe, which was in Rtools 3.5, is lacking in Rtools 4.0 and I couldn't build the package with cmake. 
Fortunately, it is possible to install Rtools 3.5 without conflict and make the build, but it makes the installation of XGboost a bit painfull. So I suggest to add gendef.exe in rtools40 (but to be honest, I'm quite new to this and it may be a bad idea).

Sincerely,
Maxime

**Comment by jeroen** [comment]
Gendef is part of the mingw-w64 tools package, you can install it in rtools40 like so:

```sh
pacman -S mingw-w64-{i686,x86_64}-tools
```

Maybe you are right that it would be better to preinstall this in rtools40.

**Comment by Maxime2506** [comment]
Glad to know there's a more elegant solution than mine. Thanks.
M.

**Comment by jeroen** [comment]
Fixed in https://github.com/r-windows/rtools-installer/commit/eab1f4deea20487e151405eac0d57d9618aacfb7
