### ISSUE TITLE
Multilib on Windows with Rtools 4.0

### ISSUE THREAD

**Issue by reedacartwright** [r-windows/rtools-packages#108]
I have an in-development package that wraps a C/C++ library. That library depends on CMake to compile a bundled library. My understanding is that it was not possible to generate both 32-bit and 64-bit libraries on windows in the configuration. Has Rtools 4.0 changed anything? Are their recommendations to getting this to succeed?

**Comment by jeroen** [comment]
You shouldn't build both 32 and 64 bit libraries in the configuration. In fact you shouldn't worry at all about multilib in the configuration. Your configure script (if any) should just target the current toolchain and architecture that it was invoked with.

R will then run this configure twice (once for each target) if it wants to build a multilib.

**Comment by reedacartwright** [comment]
I'll look at httpuv. Thanks.

**Comment by reedacartwright** [comment]
I looked at httpuv and used its design to ditch the configure scripts. Thanks for the help.
