### ISSUE TITLE
Managing library size

### ISSUE THREAD

**Issue by richardbeare** [r-windows/rtools-packages#125]
Hi,
This one may be a bit off the wall. I'm still working on the SimpleITK package build. While I have success on local systems I struggle to get the build to complete in time on Azure pipelines. One option that makes things considerably faster on linux is to build ITK and SimpleITK as shared libraries, which leads to the final .so file in R being about 7M instead of 700M. Copying all the shared objects into the package hierarchy produces a working package. I am struggling to achieve the same thing under rtools. My problem at the moment is the various low level itk shared libraries all end up exporting pthreads functions and I get errors when I attempt to link higher level ITK libraries. I've tried various options to disable the linking of system libraries (such as -nodefaultlibs) with the aim of including the necessary libs when linking the final executable. However I then get stuck with missing symbols while building the problem libraries, and no combination of -Wl,--unresolved-symbols=ignore that I can find will fix the problem. As far as I can see, all the rtools packages create libXXX.a files, without any shared libraries outside the R package. Does any of this sound remotely familiar, and if so, what approaches should I look into?

Thanks

**Comment by jeroen** [comment]
You're asking many things here, I'll try to give some answers:

> As far as I can see, all the rtools packages create libXXX.a files, without any shared libraries outside the R package.

Yes that is correct, these are called __static libraries__. See the [readme](https://github.com/r-windows/rtools-packages#contributing-to-rtools-packages).

> However I then get stuck with missing symbols while building the problem libraries, and no combination of -Wl,--unresolved-symbols=ignore that I can find will fix the problem. A

This probably means you are missing a linker flag to some dependency. When you do static linking, you need to explicitly link all of the static libraries: `-lfoo -lbar -lbaz`.

> One option that makes things considerably faster on linux is to build ITK and SimpleITK as shared libraries, which leads to the final .so file in R being about 7M instead of 700M. 

I'm not sure how you end up with a 700M file, perhaps it has debugging symbols. You can either try to build with `-O2` or use `strip` to remove debug symbols from the static libraries.

**Comment by jeroen** [comment]
I think this is solved via https://github.com/r-windows/rtools-packages/pull/120
