### ISSUE TITLE
ld error and binutils versioning best practice?

### ISSUE THREAD

**Issue by ihnorton** [r-windows/rtools-packages#151]
Hi @jeroen, do we need to declare a dependency on `"${MINGW_PACKAGE_PREFIX}-binutils"` in order to have a (relatively) stable binutils version?

We are hitting a [build error](https://github.com/TileDB-Inc/rtools-packages/runs/1196851630?check_suite_focus=true) while testing a release candidate -- this is in the cmake compiler checks, before even generating the project:

```
D:/a/_temp/msys/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: unrecognized option '--default-image-base-high'
```

As far as I can tell, this is quite similar to [this issue](https://github.com/msys2/MINGW-packages/issues/6986) which is caused by a change in the binutils default LDFLAGS.

I see that you are pulling in [msys2 binutils by default here](https://github.com/r-windows/rtools-packages/commit/4375608e756e4dca5c55a110a380a4d9b654f4df#diff-a6aeb3ad30e58660ab86c449a9fd3c0aR24), which I suppose means that the msys2 binutils is used unless a package explicitly mentions binutils in `makedepends`?

**Comment by ihnorton** [comment]
Actually, test build finished -- I tried adding the dependency, but still get the same error: [build log here](https://github.com/TileDB-Inc/rtools-packages/runs/1197022047?check_suite_focus=true).

**Comment by jeroen** [comment]
I think this has nothing to do with tiledb; there is are some temporary issues with the upstream msys2 server that causes the CI to fail to properly install the compiler. Hopefully it will be fixed soon. Will try again on monday :)

**Comment by ihnorton** [comment]
Yes, I've seen [that issue](https://github.com/msys2/MSYS2-packages/issues/2171), which has blocked my attempts to [work around](https://github.com/TileDB-Inc/rtools-packages/actions/runs/284548582) the binutils issue here (by putting the rtools binutils first in PATH).

But in the failing gh action logs I linked, there were no package download failures (AFAICT), so I think there is also a separate issue with binutils versioning.

**Comment by ihnorton** [comment]
(yes I agree it is unrelated to TileDB -- the error is during an initial cmake compiler check)

**Comment by jeroen** [comment]
OK let me test it locally in a vm. But I really don't think this has anything to do with the compiler, just some infra issue.

**Comment by ihnorton** [comment]
Thanks.

Just noting:
- our rtools40 CI builds against the same SHA were fine (see [here](https://github.com/TileDB-Inc/TileDB/runs/1199271896?check_suite_focus=true))
- the msys2 target failed with the [same](https://github.com/TileDB-Inc/TileDB/runs/1199271890?check_suite_focus=true) error as seen in the `rtools-packages` build linked above.

**Comment by jeroen** [comment]
I am seeing that error also in https://github.com/r-windows/rtools-packages/pull/152 however it builds fine locally on my Windows VM...

**Comment by ihnorton** [comment]
Do you have [msys2 binutils](https://github.com/r-windows/rtools-packages/blob/master/ci-build.sh#L32) installed in your VM ?

**Comment by jeroen** [comment]
OK I think I see the problem, msys2 added a default flag `--default-image-base-high` in https://github.com/msys2/MSYS2-packages/commit/a5855c6458afc6a62628af2ef2a8d5db2d636637 however that flag is not supported by gcc-8 that we use in rtools-packages.

**Comment by jeroen** [comment]
OK so there are indeed 2 issues: they introduced a new default linking flag that requires the latest binutils, which is conflated by the fact that the server is down so the CI fails to update to the latest binutils.

Hopefully the latter problem will solve itself soon, and then at least your msys2 builds will pass. And then I'll see if I need something to keep things working with rtools gcc-8.
