### ISSUE TITLE
Bug report: unable to install source packages with Rtools installed

### ISSUE THREAD

**Issue by XiaoyuZeng** [r-windows/rtools-packages#222]
Hi all.

I installed the latest R and Rtools, and I followed the guidelines to test the installation of Rtools **(rtools40v2-x86_64.exe for windows10)** . I verified that _make_ can be found, but I still could not install an R package from source.

Does that mean Rtools is not been install successfully? I recently failed to install a package from Github, thus I wondered it's related to the function of Rtools.

**warnings for can not installing package from source:**
> > Sys.which("make")
>                               make 
> "c:\\rtools40\\usr\\bin\\make.exe" 
> > install.packages("jsonlite", type = "source",dependencies=TRUE)
> 还安装相依关系‘proxy’, ‘e1071’, ‘wk’, ‘R.cache’, ‘classInt’, ‘DBI’, ‘s2’, ‘units’, ‘plyr’, ‘R.rsp’, ‘sf’
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/proxy_0.4-26.tar.gz'
> Content type 'application/octet-stream' length 116286 bytes (113 KB)
> downloaded 113 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/e1071_1.7-8.tar.gz'
> Content type 'application/octet-stream' length 581347 bytes (567 KB)
> downloaded 567 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/wk_0.5.0.tar.gz'
> Content type 'application/octet-stream' length 138686 bytes (135 KB)
> downloaded 135 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/R.cache_0.15.0.tar.gz'
> Content type 'application/octet-stream' length 34692 bytes (33 KB)
> downloaded 33 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/classInt_0.4-3.tar.gz'
> Content type 'application/octet-stream' length 403884 bytes (394 KB)
> downloaded 394 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/DBI_1.1.1.tar.gz'
> Content type 'application/octet-stream' length 743802 bytes (726 KB)
> downloaded 726 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/s2_1.0.6.tar.gz'
> Content type 'application/octet-stream' length 1605788 bytes (1.5 MB)
> downloaded 1.5 MB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/units_0.7-2.tar.gz'
> Content type 'application/octet-stream' length 855840 bytes (835 KB)
> downloaded 835 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/plyr_1.8.6.tar.gz'
> Content type 'application/octet-stream' length 401191 bytes (391 KB)
> downloaded 391 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/R.rsp_0.44.0.tar.gz'
> Content type 'application/octet-stream' length 823684 bytes (804 KB)
> downloaded 804 KB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/sf_1.0-2.tar.gz'
> Content type 'application/octet-stream' length 3645982 bytes (3.5 MB)
> downloaded 3.5 MB
> 
> trying URL 'https://mirrors.bfsu.edu.cn/CRAN/src/contrib/jsonlite_1.7.2.tar.gz'
> Content type 'application/octet-stream' length 421716 bytes (411 KB)
> downloaded 411 KB
> 
> Warning in install.packages :
>   installation of package ‘proxy’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘wk’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘R.cache’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘DBI’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘units’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘plyr’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘jsonlite’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘e1071’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘s2’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘R.rsp’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘classInt’ had non-zero exit status
> Warning in install.packages :
>   installation of package ‘sf’ had non-zero exit status
> 
> The downloaded source packages are in
> 	‘C:\Users\xiaoy\AppData\Local\Temp\RtmpAjZyyX\downloaded_packages’

**session info:**

> > sessionInfo()
> R version 4.1.1 (2021-08-10)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 18363)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936   
> [3] LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                              
> [5] LC_TIME=Chinese (Simplified)_China.936    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> loaded via a namespace (and not attached):
> [1] compiler_4.1.1 tools_4.1.1

**Comment by jeroen** [comment]
It looks like there is a problem with your internet, because the download already fails before the installation starts

**Comment by XiaoyuZeng** [comment]
> It looks like there is a problem with your internet, because the download already fails before the installation starts

I'm not sure about whether this is due to internet problem because I can download and install the package after deleting the requirement that 'source=TRUE'.

> > install.packages("jsonlite")
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/jsonlite_1.7.2.zip'
> Content type 'application/zip' length 544266 bytes (531 KB)
> downloaded 531 KB
> 
> package ‘jsonlite’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\xiaoy\AppData\Local\Temp\RtmpyKU9tV\downloaded_packages
