### ISSUE TITLE
VTK update to 9.2.2

### ISSUE THREAD

**Issue by astamm** [r-windows/rtools-packages#272]
Hi @jeroen. Would it be possible to update the VTK build to version `v9.2.2` please?

**Comment by astamm** [comment]
Also can you build copy binaries on `rwinlib` after the update please?

**Comment by jeroen** [comment]
Can you send a pr

**Comment by astamm** [comment]
Done. You should have received PR #273.

**Comment by jeroen** [comment]
OK I have copied them to rwinlib.
