### ISSUE TITLE
Using NLOPT 2.6.1

### ISSUE THREAD

**Issue by aadler** [r-windows/rtools-packages#62]
Hi, @jeroen .

You may be interested in https://github.com/aadler/nloptr/blob/Windows_2.6_plus/INSTALL_Windows.md if you want to update nloptr compilation from 2.4.2 to 2.6.1.

**Comment by jeroen** [comment]
I don't understand what I need to do with this. You can send a PR for https://github.com/r-windows/rtools-packages/blob/master/mingw-w64-nlopt/PKGBUILD if you want to propose an update.
