### ISSUE TITLE
R 4.0 Path to rtools in Windows

### ISSUE THREAD

**Issue by dmenne** [r-windows/rtools-packages#99]
- Uninstalled old R-Tools, removed all PATH related to rtools
- Uninstalled R 3.5
- Installed R 4.0 RC, updated libraries all ok when no rebuild required.
- Installed rtools in default directors rtools40 with windows installer.
- Added path to C:\rtools40\mingw64\bin. c++ and g++ can be called from command line
- https://cloud.r-project.org/bin/windows/testing/rtools40.html: No path set in .Renviron

- Rtools from R not found. Tried dozens of paths variants
```
> pkgbuild::with_build_tools()
Fehler: Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
> devtools::find_rtools()
WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/rtools40 has been deleted.
Please download and install Rtools custom from https://cran.r-project.org/bin/windows/Rtools/.
```

**Comment by jeroen** [comment]
We are still migrating the windows infrastructure. Please try again after the weekend...

**Comment by jeroen** [comment]
This should be fixed now.
